# ██      ██                          ██                         ██
#░██     ░██  ██   ██ ██████         ░██                        ░██
#░██     ░██ ░░██ ██ ░██░░░██ ██████ ░██  ██████   ███████      ░██
#░██████████  ░░███  ░██  ░██░░██░░█ ░██ ░░░░░░██ ░░██░░░██  ██████
#░██░░░░░░██   ░██   ░██████  ░██ ░  ░██  ███████  ░██  ░██ ██░░░██
#░██     ░██   ██    ░██░░░   ░██    ░██ ██░░░░██  ░██  ░██░██  ░██
#░██     ░██  ██     ░██     ░███    ███░░████████ ███  ░██░░██████
#░░      ░░  ░░      ░░      ░░░    ░░░  ░░░░░░░░ ░░░   ░░  ░░░░░░                             
#  
# by hyprtk (Kori Tk) (2026)
# ----------------------------------------------------- 

# ----------------------------------------------------- 
# Keyboard Layout
# ----------------------------------------------------- 
# $keyboardlayout=de
$keyboardlayout=gb

# ----------------------------------------------------- 
# Monitor Setup
# See https://wiki.hyprland.org/Configuring/Monitors/
# ----------------------------------------------------- 
# monitor=,3840x1080@144,auto,1
# monitor=,2560x1440@120,auto,1
# monitor=,1920x1080@144,auto,1
monitor=,preferred,auto,1

# ----------------------------------------------------- 
# Autostart & Environment
# ----------------------------------------------------- 
source = ~/manjaro-dots/hypr/conf/environment.conf
source = ~/manjaro-dots/hypr/conf/autostart.conf

# ----------------------------------------------------- 
# Load pywal color file
# ----------------------------------------------------- 
source = ~/.cache/wal/colors-hyprland.conf

# ----------------------------------------------------- 
# Load configuration files
# ----------------------------------------------------- 
source = ~/manjaro-dots/hypr/conf/keyboard.conf
source = ~/manjaro-dots/hypr/conf/window.conf
source = ~/manjaro-dots/hypr/conf/decoration.conf
source = ~/manjaro-dots/hypr/conf/layouts.conf
source = ~/manjaro-dots/hypr/conf/misc.conf
source = ~/manjaro-dots/hypr/conf/keybindings.conf
source = ~/manjaro-dots/hypr/conf/windowrules.conf
source = ~/manjaro-dots/hypr/conf/nvidia.conf

# ----------------------------------------------------- 
# Animation
# ----------------------------------------------------- 
source = ~/manjaro-dots/hypr/conf/animations-low.conf
# source = ~/manjaro-dots/hypr/conf/animations-high.conf
# = Source for hyprviz
source = ./hyprviz.conf
